/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{ts,tsx}',
    './examples/src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'brand-blue': '#0E75DD',
        'brand-danger': '#eb3f47',
        'brand-success': '#70be44',
        'brand-warning': '#f68d38',
        'brand-primary-dark-gray': '#1E2127',
        'brand-primary-gray': '#6D7584',
        'brand-primary-light-gray': '#979EAB',
        'dark-gray': '#5c7288',
        'bg-blue-50': '#e6f1fd',
        'bg-gray-90': '#F7F8FA',
        'gray-lighter': '#d8dde3',
        'border-color': '#DBE0EA',
        'time-blocked': '#a1000c',
        'time-dns': '#dcc9e5',
        'time-ssl': '#e78057',
        'time-connect': '#db8553',
        'time-send': '#3c96c4',
        'time-wait': '#7ca0bf',
        'time-receive': '#65b955',
        'time-queueing': '#ccc',
        'white-0': '#000',
        'white-100': '#fff',
        'white-33': '#555',
        'white-39': '#646464',
        'white-50': '#808080',
        'white-80': '#ccc',
        'white-90': '#e6e6e6',
      },
      fontSize: {
        'base': '14px',
        'bigger': '16px',
        'huge': '42px',
        'large': '18px',
        'small': '12px',
        'h1': '36px',
        'h2': '30px',
        'h3': '24px',
        'h4': '18px',
        'h5': '14px',
        'h6': '12px',
      },
      borderRadius: {
        'base': '4px',
      },
      spacing: {
        'xs': '4px',
        'xs-s': '8px',
        's': '12px',
        'm': '16px',
        'l': '20px',
        'xl': '28px',
        'xxl': '36px',
        'xxxl': '44px',
      },
      screens: {
        'xs': '480px',
        'grid-sm': '576px',
        'sm': '768px',
        'md': '992px',
        'lg': '1200px',
      },
      keyframes: {
        spin: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'spin-slow': 'spin 1.4s infinite linear',
      },
    },
  },
  plugins: [],
};
